wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    code_path: code/decision_transformer/generate_dataset.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1660914956
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 16
      4: 3.8.12
      5: 0.12.9
      8:
      - 5
env_name:
  desc: null
  value: VizdoomBasic-v0
num_cpu:
  desc: null
  value: 6
policy_type:
  desc: null
  value: CnnPolicy
total_timesteps:
  desc: null
  value: 10000
